---
- name: Prepare Jira Server Role test
  hosts: all
  become: true
  tasks:

   # Install which command
   - name: "({{ ansible_distribution }}) - GFS::PREPARE - Install which command"
     package:
      name: "{{ item }}"
      state: present
     loop:
      - which
     when:
      - ansible_os_family == "RedHat"

   # Install Open JDK 11
   - name: "({{ ansible_distribution }}) - GFS::PREPARE - Install OpenJDK 11"
     include_role:
      name: jetune.java
     vars:
      from_repo: false
      implementation: OPENJDK
      v_major: 11
      v_minor: 0.1
      build: 13
      os: linux
      arch: x64
      checksum: sha256:7a6bb980b9c91c478421f865087ad2d69086a0583aeeb9e69204785e8e97dcfd
      alternative_priority: 300
      is_default: true
